### ISSUE TITLE
Thriftrw does not support go.tag

### ISSUE THREAD

**Issue by sunaaron** [thriftrw/thriftrw-node#140]
Hi there, 

I am using thrift's go.tag feature, please see here 

http://stackoverflow.com/questions/31319534/control-golang-annotations-in-thrift-generated-code

However, when I using tcurl (using thriftw) to test any thrift service with go.tag feature, I got the following error:

Thrift Syntax Error
Expected ")", "=", identifier or list separator but "\\" found.

Verified the thrift file works fine with other compiler. 

Thanks
Aaron

**Comment by kriskowal** [comment]
verified locally

**Comment by mattgode** [comment]
+1 on this. I had an issue open a few months back about this exact same issue, but it appears to somehow have gotten closed.

**Comment by kriskowal** [comment]
Fixed by #141
